-- Database schema for 8 Certificate Services

-- 1. Income Certificates
CREATE TABLE IF NOT EXISTS `income_certificates` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `full_name` VARCHAR(255) NOT NULL,
    `aadhaar_number` VARCHAR(12) NOT NULL,
    `mobile_number` VARCHAR(10) NOT NULL,
    `email` VARCHAR(255),
    `pan_number` VARCHAR(10),
    `dob` DATE NOT NULL,
    `gender` ENUM('Male', 'Female', 'Other') NOT NULL,
    `occupation` VARCHAR(255),
    `annual_income` DECIMAL(15, 2) NOT NULL,
    `income_source` VARCHAR(255),
    `purpose` VARCHAR(255),
    `house_no` VARCHAR(255),
    `street` VARCHAR(255),
    `village` VARCHAR(255),
    `taluka` VARCHAR(255),
    `district` VARCHAR(255),
    `state` VARCHAR(255),
    `pincode` VARCHAR(6),
    `aadhaar_card_url` VARCHAR(255),
    `ration_card_url` VARCHAR(255),
    `tax_receipt_url` VARCHAR(255),
    `income_proof_url` VARCHAR(255),
    `self_declaration_url` VARCHAR(255),
    `photo_url` VARCHAR(255),
    `other_docs_url` VARCHAR(255),
    `status` ENUM('Pending', 'Processing', 'Completed', 'Rejected') DEFAULT 'Pending',
    `reference_id` VARCHAR(20) UNIQUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Caste Certificates
CREATE TABLE IF NOT EXISTS `caste_certificates` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `full_name` VARCHAR(255) NOT NULL,
    `aadhaar_number` VARCHAR(12) NOT NULL,
    `mobile_number` VARCHAR(10) NOT NULL,
    `email` VARCHAR(255),
    `dob` DATE NOT NULL,
    `gender` ENUM('Male', 'Female', 'Other') NOT NULL,
    `category` VARCHAR(50) NOT NULL,
    `sub_caste` VARCHAR(255),
    `religion` VARCHAR(50),
    `father_name` VARCHAR(255),
    `father_caste` VARCHAR(255),
    `mother_name` VARCHAR(255),
    `domicile_status` VARCHAR(255),
    `house_no` VARCHAR(255),
    `street` VARCHAR(255),
    `village` VARCHAR(255),
    `district` VARCHAR(255),
    `state` VARCHAR(255),
    `pincode` VARCHAR(6),
    `father_aadhaar` VARCHAR(12),
    `father_occupation` VARCHAR(255),
    `existing_certificate_no` VARCHAR(100),
    `previously_issued` ENUM('Yes', 'No'),
    `duration_of_residence` VARCHAR(100),
    `aadhaar_card_url` VARCHAR(255),
    `ration_card_url` VARCHAR(255),
    `school_leaving_url` VARCHAR(255),
    `caste_proof_url` VARCHAR(255),
    `father_caste_cert_url` VARCHAR(255),
    `self_declaration_url` VARCHAR(255),
    `photo_url` VARCHAR(255),
    `status` ENUM('Pending', 'Processing', 'Completed', 'Rejected') DEFAULT 'Pending',
    `reference_id` VARCHAR(20) UNIQUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Domicile Certificates
CREATE TABLE IF NOT EXISTS `domicile_certificates` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `full_name` VARCHAR(255) NOT NULL,
    `aadhaar_number` VARCHAR(12) NOT NULL,
    `mobile_number` VARCHAR(10) NOT NULL,
    `email` VARCHAR(255),
    `dob` DATE NOT NULL,
    `gender` ENUM('Male', 'Female', 'Other') NOT NULL,
    `years_in_state` INT,
    `occupation` VARCHAR(255),
    `reason` VARCHAR(255),
    `house_no` VARCHAR(255),
    `street` VARCHAR(255),
    `village` VARCHAR(255),
    `district` VARCHAR(255),
    `state` VARCHAR(255),
    `pincode` VARCHAR(6),
    `aadhaar_card_url` VARCHAR(255),
    `ration_card_url` VARCHAR(255),
    `birth_cert_url` VARCHAR(255),
    `school_leaving_url` VARCHAR(255),
    `residence_proof_url` VARCHAR(255),
    `self_declaration_url` VARCHAR(255),
    `photo_url` VARCHAR(255),
    `status` ENUM('Pending', 'Processing', 'Completed', 'Rejected') DEFAULT 'Pending',
    `reference_id` VARCHAR(20) UNIQUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Birth Certificates
CREATE TABLE IF NOT EXISTS `birth_certificates` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `child_name` VARCHAR(255) NOT NULL,
    `gender` ENUM('Male', 'Female', 'Other') NOT NULL,
    `dob` DATE NOT NULL,
    `time_of_birth` TIME,
    `place_of_birth` ENUM('Hospital', 'Home') NOT NULL,
    `hospital_name` VARCHAR(255),
    `registration_date` DATE,
    `father_name` VARCHAR(255),
    `father_aadhaar` VARCHAR(12),
    `father_mobile` VARCHAR(10),
    `father_occupation` VARCHAR(255),
    `mother_name` VARCHAR(255),
    `mother_aadhaar` VARCHAR(12),
    `mother_mobile` VARCHAR(10),
    `mother_occupation` VARCHAR(255),
    `house_no` VARCHAR(255),
    `street` VARCHAR(255),
    `village` VARCHAR(255),
    `district` VARCHAR(255),
    `state` VARCHAR(255),
    `pincode` VARCHAR(6),
    `registration_type` ENUM('Normal', 'Late') NOT NULL,
    `delay_reason` TEXT,
    `hospital_report_url` VARCHAR(255),
    `parents_aadhaar_url` VARCHAR(255),
    `address_proof_url` VARCHAR(255),
    `marriage_certificate_url` VARCHAR(255),
    `affidavit_url` VARCHAR(255),
    `status` ENUM('Pending', 'Processing', 'Completed', 'Rejected') DEFAULT 'Pending',
    `reference_id` VARCHAR(20) UNIQUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Death Certificates
CREATE TABLE IF NOT EXISTS `death_certificates` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `deceased_name` VARCHAR(255) NOT NULL,
    `deceased_aadhaar` VARCHAR(12) NOT NULL,
    `gender` ENUM('Male', 'Female', 'Other') NOT NULL,
    `dob` DATE,
    `date_of_death` DATE NOT NULL,
    `time_of_death` TIME,
    `place_of_death` ENUM('Hospital', 'Home', 'Other') NOT NULL,
    `hospital_name` VARCHAR(255),
    `cause_of_death` VARCHAR(255),
    `applicant_name` VARCHAR(255) NOT NULL,
    `applicant_aadhaar` VARCHAR(12) NOT NULL,
    `relationship` VARCHAR(100) NOT NULL,
    `mobile_number` VARCHAR(10) NOT NULL,
    `email` VARCHAR(255),
    `house_no` VARCHAR(255),
    `street` VARCHAR(255),
    `village` VARCHAR(255),
    `taluka` VARCHAR(255),
    `district` VARCHAR(255),
    `state` VARCHAR(255),
    `pincode` VARCHAR(6),
    `registration_type` ENUM('Normal', 'Late') NOT NULL,
    `delay_reason` TEXT,
    `death_report_url` VARCHAR(255),
    `deceased_aadhaar_url` VARCHAR(255),
    `applicant_aadhaar_url` VARCHAR(255),
    `address_proof_url` VARCHAR(255),
    `status` ENUM('Pending', 'Processing', 'Completed', 'Rejected') DEFAULT 'Pending',
    `reference_id` VARCHAR(20) UNIQUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Marriage Certificates
CREATE TABLE IF NOT EXISTS `marriage_certificates` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `groom_name` VARCHAR(255) NOT NULL,
    `groom_aadhaar` VARCHAR(12) NOT NULL,
    `groom_dob` DATE NOT NULL,
    `groom_age` INT,
    `groom_occupation` VARCHAR(255),
    `groom_mobile` VARCHAR(10),
    `groom_email` VARCHAR(255),
    `bride_name` VARCHAR(255) NOT NULL,
    `bride_aadhaar` VARCHAR(12) NOT NULL,
    `bride_dob` DATE NOT NULL,
    `bride_age` INT,
    `bride_occupation` VARCHAR(255),
    `bride_mobile` VARCHAR(10),
    `bride_email` VARCHAR(255),
    `date_of_marriage` DATE NOT NULL,
    `place_of_marriage` VARCHAR(255) NOT NULL,
    `marriage_address` TEXT,
    `type_of_marriage` ENUM('Religious', 'Court', 'Other') NOT NULL,
    `w1_name` VARCHAR(255),
    `w1_aadhaar` VARCHAR(12),
    `w1_address` TEXT,
    `w1_mobile` VARCHAR(10),
    `w2_name` VARCHAR(255),
    `w2_aadhaar` VARCHAR(12),
    `w2_address` TEXT,
    `w2_mobile` VARCHAR(10),
    `groom_aadhaar_url` VARCHAR(255),
    `bride_aadhaar_url` VARCHAR(255),
    `invitation_card_url` VARCHAR(255),
    `venue_proof_url` VARCHAR(255),
    `marriage_photos_url` VARCHAR(255),
    `w1_aadhaar_url` VARCHAR(255),
    `w2_aadhaar_url` VARCHAR(255),
    `w1_photo_url` VARCHAR(255),
    `w2_photo_url` VARCHAR(255),
    `address_proof_url` VARCHAR(255),
    `status` ENUM('Pending', 'Processing', 'Completed', 'Rejected') DEFAULT 'Pending',
    `reference_id` VARCHAR(20) UNIQUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. EWS Certificates
CREATE TABLE IF NOT EXISTS `ews_certificates` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `full_name` VARCHAR(255) NOT NULL,
    `aadhaar_number` VARCHAR(12) NOT NULL,
    `dob` DATE NOT NULL,
    `gender` ENUM('Male', 'Female', 'Other') NOT NULL,
    `mobile_number` VARCHAR(10) NOT NULL,
    `email` VARCHAR(255),
    `category` VARCHAR(50) DEFAULT 'General / Open',
    `father_name` VARCHAR(255),
    `mother_name` VARCHAR(255),
    `spouse_name` VARCHAR(255),
    `family_members_count` INT,
    `family_occupation` VARCHAR(100),
    `income_salary` DECIMAL(15, 2),
    `income_agri` DECIMAL(15, 2),
    `income_business` DECIMAL(15, 2),
    `income_other` DECIMAL(15, 2),
    `total_annual_income` DECIMAL(15, 2),
    `flat_size` DECIMAL(10, 2),
    `plot_size` DECIMAL(10, 2),
    `location_type` ENUM('Municipal', 'Non-Municipal'),
    `agri_land_details` TEXT,
    `ownership_status` VARCHAR(255),
    `income_cert_url` VARCHAR(255),
    `proof_of_income_urls` TEXT, -- JSON or comma separated
    `property_docs_urls` TEXT, -- JSON or comma separated
    `id_proof_url` VARCHAR(255),
    `residence_proof_url` VARCHAR(255),
    `self_declaration_url` VARCHAR(255),
    `photo_url` VARCHAR(255),
    `caste_cert_url` VARCHAR(255),
    `status` ENUM('Pending', 'Processing', 'Completed', 'Rejected') DEFAULT 'Pending',
    `reference_id` VARCHAR(20) UNIQUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. Non-Creamy Layer Certificates
CREATE TABLE IF NOT EXISTS `non_creamy_layer_certificates` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `full_name` VARCHAR(255) NOT NULL,
    `aadhaar_number` VARCHAR(12) NOT NULL,
    `dob` DATE NOT NULL,
    `gender` ENUM('Male', 'Female', 'Other') NOT NULL,
    `mobile_number` VARCHAR(10) NOT NULL,
    `email` VARCHAR(255),
    `category` VARCHAR(50) DEFAULT 'OBC',
    `sub_caste` VARCHAR(255),
    `caste_cert_number` VARCHAR(100),
    `issuing_authority` VARCHAR(255),
    `issue_date` DATE,
    `father_name` VARCHAR(255),
    `mother_name` VARCHAR(255),
    `parent_occupation` VARCHAR(255),
    `income_year1` DECIMAL(15, 2),
    `income_year2` DECIMAL(15, 2),
    `income_year3` DECIMAL(15, 2),
    `income_source` VARCHAR(100),
    `marital_status` ENUM('Unmarried', 'Married'),
    `caste_before_marriage` VARCHAR(255),
    `husband_name` VARCHAR(255),
    `marriage_reg_details` TEXT,
    `gazette_name_change` VARCHAR(255),
    `is_migrant` ENUM('Yes', 'No'),
    `previous_state` VARCHAR(255),
    `previous_district` VARCHAR(255),
    `id_proof_url` VARCHAR(255),
    `address_proof_url` VARCHAR(255),
    `caste_cert_url` VARCHAR(255),
    `income_proof_year1_url` VARCHAR(255),
    `income_proof_year2_url` VARCHAR(255),
    `income_proof_year3_url` VARCHAR(255),
    `photo_url` VARCHAR(255),
    `school_leaving_url` VARCHAR(255),
    `caste_affidavit_url` VARCHAR(255),
    `pre_marriage_caste_url` VARCHAR(255),
    `marriage_cert_url` VARCHAR(255),
    `gazette_copy_url` VARCHAR(255),
    `father_caste_cert_url` VARCHAR(255),
    `status` ENUM('Pending', 'Processing', 'Completed', 'Rejected') DEFAULT 'Pending',
    `reference_id` VARCHAR(20) UNIQUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
